name: Run Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: install
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script
        run: |
          python main.py
        env:
          'HELLO KITTY': ${{secrets.HELLO_KITTY}}
