name: Run Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELLO_KITTY: ${{ secrets.HELLO_KITTY }}
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: install
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script
        run: |
          python main.py
      - name: bah
        run: echo ${{secrets.HELLO_KITTY}}
      - if: ${{ env.HELLO_KITTY != '' }}
        run: echo 'This step will only run if the secret has a value set.'
      - if: ${{ env.HELLO_KITTY == '' }}
        run: echo 'This step will only run if the secret does not have a value set.'
