name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - with:
          python-version: 3.8 #install the python needed
      - name: execute py script
      - run: |
          python main.py
        env:
          'HELLO KITTY': 'HELLO BEAR'
        
